FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y default-jre && \
    apt-get clean;

WORKDIR /app

COPY requirements-spark.txt .
RUN pip install --no-cache-dir -r requirements-spark.txt

